name = "iknowwhatyoufuture"
compatibility_date = "2024-01-01"

[env.production]
# 确保支持SPA路由
[[env.production.routes]]
pattern = "/*"
custom_domain = true

# 静态资源缓存
[[env.production.routes]]
pattern = "/assets/*"
custom_domain = true
